repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-toml
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: pretty-format-json
        args:
          - --autofix
          - --no-sort-keys
      - id: trailing-whitespace
      - id: no-commit-to-branch
        args: ['--branch', 'master']

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    - id: detect-secrets
      args: ["--disable-plugin", "Base64HighEntropyString", "--disable-plugin", "KeywordDetector", "--exclude-files", "README.md"]

  # Repo specific
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.14.2
    hooks:
    - id: helm-docs
      args:
      - --chart-search-root=.
