{{- if .Values.service.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.fullname" . }}
  {{- include "generic.labels" . | nindent 2 }}
{{- with .Values.service.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports: {{ toYaml .Values.service.ports | nindent 4 }}
  selector:
    app.kubernetes.io/name: {{ coalesce .Values.appNameLabelOverride ( include "app.name" . ) }}
    app.kubernetes.io/instance: {{ coalesce .Values.appInstanceLabelOverride .Release.Name }}
{{- end }}
